# Generated by Django 5.2.12 on 2026-04-28 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blootie_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='profesor_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_estudiantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
