# Generated by Django 5.2.12 on 2026-04-28 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blootie_app', '0002_actividad_creado_por_perfil_profesor_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='icono',
            field=models.CharField(default='🏆', max_length=10),
        ),
        migrations.AddField(
            model_name='progreso',
            name='actividad_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_progreso', to='blootie_app.actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
