# Generated by Django 5.2.12 on 2026-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blootie_app', '0003_logro_icono_progreso_actividad_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('esta_activa', models.BooleanField(default=True)),
            ],
        ),
    ]
