# Generated by Django 6.0.4 on 2026-05-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blootie_app', '0004_configuracionactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('portada', models.ImageField(upload_to='cuentos/portadas/')),
                ('contenido', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='cuentos/audios/')),
            ],
        ),
    ]
